### ISSUE TITLE
Support other options from collections like collation or strength

### ISSUE THREAD

**Issue by luizcarlos1405** [quavedev/collections#2]
There are just a handfull of options we can use with this package at the moment. Recently I missed `collation` (to define a locale for sort purposes, like doing non-diacritic searches).

https://docs.mongodb.com/manual/reference/collation/

I'm making this issue to keep this documented. In the future this might be a bigger problem then I might take a look if we can just accept everything (probably).

**Comment by filipenevola** [comment]
We should just spread all the options then we don't need to worry about specific ones.
